// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class GooglewithangulartestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void googlewithangulartest() {
    // Test name: googlewithangulartest
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.google.com/");
    // 2 | setWindowSize | 1536x816 | 
    driver.manage().window().setSize(new Dimension(1536, 816));
    // 3 | click | name=q | 
    driver.findElement(By.name("q")).click();
    // 4 | click | css=.sbhl .wM6W7d > span | 
    driver.findElement(By.cssSelector(".sbhl .wM6W7d > span")).click();
    // 5 | click | id=rcnt | 
    driver.findElement(By.id("rcnt")).click();
    // 6 | click | name=q | 
    driver.findElement(By.name("q")).click();
    // 7 | type | name=q | angular notes
    driver.findElement(By.name("q")).sendKeys("angular notes");
    // 8 | click | css=.sbhl .wM6W7d > span | 
    driver.findElement(By.cssSelector(".sbhl .wM6W7d > span")).click();
    // 9 | click | css=div:nth-child(2) > .tF2Cxc > .yuRUbf .LC20lb | 
    driver.findElement(By.cssSelector("div:nth-child(2) > .tF2Cxc > .yuRUbf .LC20lb")).click();
    // 10 | click | css=.ng-star-inserted:nth-child(2) .level-1 > span | 
    driver.findElement(By.cssSelector(".ng-star-inserted:nth-child(2) .level-1 > span")).click();
    // 11 | click | css=nav > .ng-star-inserted:nth-child(2) > .ng-star-inserted > .heading-children > .ng-star-inserted:nth-child(2) > .ng-star-inserted > .vertical-menu-item > span | 
    driver.findElement(By.cssSelector("nav > .ng-star-inserted:nth-child(2) > .ng-star-inserted > .heading-children > .ng-star-inserted:nth-child(2) > .ng-star-inserted > .vertical-menu-item > span")).click();
    // 12 | click | css=.ng-star-inserted:nth-child(2) .heading-children:nth-child(2) .heading-children:nth-child(2) > .ng-star-inserted:nth-child(1) span:nth-child(1) | 
    driver.findElement(By.cssSelector(".ng-star-inserted:nth-child(2) .heading-children:nth-child(2) .heading-children:nth-child(2) > .ng-star-inserted:nth-child(1) span:nth-child(1)")).click();
    // 13 | click | linkText=HTML | 
    driver.findElement(By.linkText("HTML")).click();
    // 14 | click | css=.main-page-content | 
    driver.findElement(By.cssSelector(".main-page-content")).click();
  }
}
